backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "galeria_settings"
    label: "Galeria Zdjęć"
    delete: false
    editor:
      preview: false
    files:
      - file: "galeria.json"
        label: "Zarządzaj Zdjęciami"
        name: "galeria"
        fields:
          - label: "Zdjęcia w realizacji"
            name: "images"
            widget: "list"
            fields:
              - {label: "Zdjęcie", name: "image", widget: "image"}
              - {label: "Tytuł / Opis", name: "title", widget: "string", required: false}
